### ISSUE TITLE
Overflow in example

### ISSUE THREAD

**Issue by rth** [argmin-rs/pyargmin#1]
Thanks for putting this together!

I was playing with the example, and on nightly the cost function in `test1.py` seems to overflow,
```
$ cd python && python test1.py
<Landweber object at 0x7f931e449660>
fufufu_3
<Executor object at 0x55ecd55fd860>
Jul 16 22:27:40.911 INFO Landweber, max_iters: 20
Jul 16 22:27:40.911 INFO iter: 0, cost: inf, best_cost: inf, cost_func_count: 0, grad_func_count: 1, jacobian_func_count: 0, hessian_func_count: 0, modify_func_count: 0, time: 0.000027998000000000002
Jul 16 22:27:40.912 INFO iter: 1, cost: inf, best_cost: test1.py:40: RuntimeWarning: overflow encountered in double_scalars
  [-2.0 * self.a + 4.0 * self.b * x**3 - 4.0 * self.b * x * y + 2.0 * x,
inf, cost_func_count: 0, grad_func_count: 2, jacobian_func_count: 0, hessian_func_count: 0, modify_func_count: 0test1.py:40: RuntimeWarning: invalid value encountered in double_scalars
  [-2.0 * self.a + 4.0 * self.b * x**3 - 4.0 * self.b * x * y + 2.0 * x,
, time: 0.000012927
Jul 16 22:27:40.912 INFO iter: 2, cost: inf, best_cost: inf, cost_func_count: 0, grad_func_count: 3, jacobian_func_count: 0, hessian_func_count: 0, modify_func_count: 0, time: 0.000011587000000000001
Jul 16 22:27:40.912 INFO iter: 3, cost: inf, best_cost: inf, cost_func_count: 0, grad_func_count: 4, jacobian_func_count: 0, hessian_func_count: 0, modify_func_count: 0, time: 0.000011242
Jul 16 22:27:40.912 INFO iter: 4, cost: inf, best_cost: inf, cost_func_count: 0, grad_func_count: 5, jacobian_func_count: 0, hessian_func_count: 0, modify_func_count: 0, time: 0.000011276
Jul 16 22:27:40.912 INFO iter: 5, cost: inf, best_cost: inf, cost_func_count: 0, grad_func_count: 6, jacobian_func_count: 0, hessian_func_count: 0, modify_func_count: 0, time: 0.000273192
```
is this the expected output?

**Comment by stefan-k** [comment]
I tried to investigate this and could see the same output (more or less). The Rust part seems to be passing ridiculously large numbers to the `gradient` function which causes the overflow. I don't recall having this problem a couple of months ago, but I may have just missed it.
I then made changes to the Rust part and tried to compile it with the latest nightly compiler but it failed at compiling the crate `mashup`, whatever that is. I'll give it a try tomorrow again, maybe it will compile with the next nightly compiler.

**Comment by rth** [comment]
> I then made changes to the Rust part and tried to compile it with the latest nightly compiler but it failed at compiling the crate mashup, whatever that is.

Yes, I saw that error at some point, but then now the project builds fine for me (still with the latest nightly), I'm not sure what I did to work around it.

**Comment by rth** [comment]
> tried to compile it with the latest nightly compiler but it failed at compiling the crate mashup, whatever that is.

Downgrading to e.g. rust `nightly-2019-04-28` (arbitrary date) is a possible workaround.

**Comment by stefan-k** [comment]
I just found this: https://github.com/PyO3/pyo3/issues/547 .
The solution seems to be to run `cargo update`.

**Comment by stefan-k** [comment]
Does it work for you? I can compile, but when I run the commands

```bash
cp target/release/lib_lib.so examples/argmin.so
cd examples
python3 test1.py
```

it fails with

```
Traceback (most recent call last):
  File "test1.py", line 15, in <module>
    import argmin
ImportError: dynamic module does not define module export function (PyInit_argmin)
```
This may be related to the update to PyO3 version 0.7.0.

**Comment by rth** [comment]
Are you sure that you are using the latest version from master? That error is typically the sign of a name mismatch between `name = "_lib"` in `Cargo.toml` and the module name,
```
#[pymodule]
fn _lib(...)
```
in `src/lib.rs`.

**Comment by stefan-k** [comment]
`Cargo.toml` is the same as the current master, but I had to adapt the `justfile` a bit. The file `target/release/_lib.so` doesn't exist on my system (but `target/release/lib_lib.so` does). 
I've moved `lib_lib.so` to `examples/argmin.so` (and not to `python/pyargmin.so` like it is the case on master). 

Thanks for pointing me into the right direction, because it seems to work for me if I change it to

```rust
#[pymodule]
fn argmin(...)
```
in `src/lib.rs`. This is however not consistent with `name = "_lib"` in `Cargo.toml`. I guess if the the module is named `_lib`, the import in the Python file has to be different as well?

**Comment by rth** [comment]
Aww, yes, I might have changed `justfiles` incorrectly. I'm just using `python setup.py install` to build ...

**Comment by stefan-k** [comment]
Ah, that explains it! After a bit of hassle I got it to work with `python setup.py install`. I noticed that it only compiles if `nightly` is the default toolchain.
It seems to work really well! Thanks for this great work!

**Comment by rth** [comment]
So it looks like the optimization diverges for some reason here are the parameter values passed to the gradient calculation,
```
gradient [1.2 1.2] 
gradient [-10.36   6.  ] 
gradient [41982.89824  2032.592  ] 
gradient [-2.95989796e+15  3.52512363e+10] 
gradient [1.03726616e+48 1.75219919e+32] 
gradient [-4.46406613e+145  2.15184217e+097] 
examples/test1.py:43: RuntimeWarning: overflow encountered in double_scalars
  + 2.0 * x, 2.0 * self.b * (y - x**2)])
gradient [            inf 3.98557728e+292]
```
even with a very small (`1e-4`) values for omega. I think would start by adding a few convergence tests in (https://github.com/argmin-rs/argmin/issues/12), just to be sure that in Rust (without adding the complexity of the Python wrapper) it works as expected.

**Comment by rth** [comment]
Aww, indeed, I had tried `set_omega` but haven't payed attention that it was a no-ops, and that it needed to be provided in the init. Thanks!

**Comment by stefan-k** [comment]
Sorry I didn't have time yesterday to have a look at it.
Did you change `omega` via the `set_omega` method? Because I just realized that all it does is print out a curse and move on ;) So far `omega` has to be set with the constructor:

```python
solver = argmin.landweber(0.001)
```
and then it works as expected. 
Sorry about the mess in this codebase, it was really just a very quick try. I really appreciate the effort you have put into this already!

**Comment by rth** [comment]
> Did you change omega via the set_omega method? Because I just realized that all it does is print out a curse and move on ;)

Yes, that was the issue.

No worries, I should have seen it, thanks for all the work you have put into argmin!
