### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by rth** [argmin-rs/pyargmin#3]
Would you mind enabling CI in this repo?

There is a `.travis-ci.yaml` that currently doesn't do anything. Though I would personally prefer CircleCI as it allows to use linux Dockers images directly. There is an example of CI config for a Python wrapper of Rust code in [vtext/.circleci/config.yaml](https://github.com/rth/vtext/blob/master/.circleci/config.yml). I can simplify and adapt that.

If this package ever gets stable enough to distribute it, there is also a Azure CI setup in [vtext/azure-pipelines.yaml](https://github.com/rth/vtext/blob/master/azure-pipelines.yml) allows building wheels for MacOS and Windows. But that's probably not useful for now.

**Comment by stefan-k** [comment]
Travis should now be [enabled](https://travis-ci.org/argmin-rs/pyargmin/). 
I have no experience with CircleCI, but I've just signed up for it and enabled the piplines for `pyargmin`, `argmin` and `argmin-core`. It would be great if you could set up a config :)

Let me know if there is more that I can do!

**Comment by rth** [comment]
Thanks @stefan-k !

I have made https://github.com/argmin-rs/pyargmin/pull/5 (still WIP) here, I don't think Travis CI would be needed here, since only nightly would work anyway and different Python versions could be tested in Circle CI. Maybe it could be worth disabling it here?

For `argmin` and `argmin-core` I could add for instance a `rust fmt` linter check if you think that it would be useful? As otherwise the existing Travis CI setup for building and running tests seems sufficient.

The reason why CircleCI is useful for building python wrappers is that those require the CentOS 5 environment to build manylinux wheels. For pure rust projects it's less critical..

**Comment by stefan-k** [comment]
Thanks for the PR!

Disabling Travis is fine with me if CircleCI is more convenient in this case. Feel free to adapt this in any way you like.

Having a `rustfmt` check in CI sounds great! Could we also enable a `clippy` check (because thats something I personally don't use often enough and that would be a good reminder). But I'm not sure if the pipeline should fail in case `clippy` has something to complain about.
